export type Workload = {
  id: string;
  customer: string;
  application: string;
  database: string;
  engine: string;
  version: string;
  hosting: string;
  size: string;
  criticality: 'Critical' | 'High' | 'Medium';
  eosRisk: 'High' | 'Medium' | 'Low';
  azureState: string;
  assessment: 'Complete' | 'In progress' | 'Not started';
  compatibility: string;
  complexity: 'Low' | 'Medium' | 'High';
  dependencies: string;
  blockers: string;
  readiness: number;
  pattern: string;
  target: string;
  rationale: string;
  benefit: string;
  considerations: string;
};

export const workloads: Workload[] = [
  {
    id: 'DB-1042',
    customer: 'Contoso Retail',
    application: 'Store Operations',
    database: 'RetailOps-Prod',
    engine: 'SQL Server',
    version: '2012 SP4',
    hosting: 'On-premises',
    size: '1.8 TB',
    criticality: 'Critical',
    eosRisk: 'High',
    azureState: 'Not in Azure',
    assessment: 'Complete',
    compatibility: '96%',
    complexity: 'Medium',
    dependencies: 'ERP API, SSIS (14)',
    blockers: 'Legacy SQL Agent jobs',
    readiness: 84,
    pattern: 'Replatform',
    target: 'Azure SQL Managed Instance',
    rationale: 'High SQL compatibility with minimal application change.',
    benefit: 'Reduce platform operations and remove EOS exposure.',
    considerations: 'Refactor two cross-database jobs before cutover.',
  },
  {
    id: 'DB-1088',
    customer: 'Fabrikam Energy',
    application: 'Field Service',
    database: 'Dispatch-Core',
    engine: 'PostgreSQL',
    version: '11.18',
    hosting: 'AWS',
    size: '640 GB',
    criticality: 'High',
    eosRisk: 'Medium',
    azureState: 'Hybrid',
    assessment: 'Complete',
    compatibility: '99%',
    complexity: 'Low',
    dependencies: 'Mobile API',
    blockers: 'None identified',
    readiness: 93,
    pattern: 'Replatform',
    target: 'Azure SQL Database',
    rationale: 'Cloud-native workload with low dependency coupling.',
    benefit: 'Consolidate cloud spend and improve elastic scale.',
    considerations: 'Validate PostgreSQL extension equivalents.',
  },
  {
    id: 'DB-1121',
    customer: 'Northwind Health',
    application: 'Patient Billing',
    database: 'BillingDW',
    engine: 'Oracle',
    version: '12c',
    hosting: 'On-premises',
    size: '4.2 TB',
    criticality: 'Critical',
    eosRisk: 'High',
    azureState: 'Landing zone ready',
    assessment: 'In progress',
    compatibility: '72%',
    complexity: 'High',
    dependencies: 'EHR, ETL, Cognos',
    blockers: 'PL/SQL package conversion',
    readiness: 58,
    pattern: 'Refactor',
    target: 'SQL Database in Microsoft Fabric',
    rationale: 'Strategic analytics workload aligned to OneLake.',
    benefit: 'Unify operational data and near-real-time analytics.',
    considerations: 'Phase PL/SQL conversion and validate regulatory controls.',
  },
  {
    id: 'DB-1156',
    customer: 'Adventure Works',
    application: 'Dealer Portal',
    database: 'DealerHub',
    engine: 'SQL Server',
    version: '2019 CU24',
    hosting: 'Azure VM',
    size: '920 GB',
    criticality: 'High',
    eosRisk: 'Low',
    azureState: 'Azure-hosted',
    assessment: 'Complete',
    compatibility: '100%',
    complexity: 'Low',
    dependencies: 'Entra ID, CRM',
    blockers: 'None identified',
    readiness: 96,
    pattern: 'Modernize',
    target: 'Azure SQL Database',
    rationale: 'Already in Azure with strong PaaS compatibility.',
    benefit: 'Eliminate VM management and enable serverless scale.',
    considerations: 'Right-size compute after a 30-day performance baseline.',
  },
  {
    id: 'DB-1194',
    customer: 'Litware Manufacturing',
    application: 'Plant MES',
    database: 'MES-Plant07',
    engine: 'SQL Server',
    version: '2008 R2',
    hosting: 'Edge datacenter',
    size: '380 GB',
    criticality: 'Critical',
    eosRisk: 'High',
    azureState: 'Not in Azure',
    assessment: 'In progress',
    compatibility: '91%',
    complexity: 'Medium',
    dependencies: 'Plant equipment, OPC',
    blockers: 'Latency and offline operations',
    readiness: 69,
    pattern: 'Replatform',
    target: 'SQL Server on Azure Local',
    rationale: 'Local processing requirement with Azure governance.',
    benefit: 'Modernize infrastructure while preserving plant resilience.',
    considerations: 'Complete network and disconnected-operations validation.',
  },
  {
    id: 'DB-1230',
    customer: 'Tailspin Toys',
    application: 'Order Management',
    database: 'Orders-Primary',
    engine: 'MySQL',
    version: '5.7',
    hosting: 'Private cloud',
    size: '210 GB',
    criticality: 'Medium',
    eosRisk: 'Medium',
    azureState: 'Not in Azure',
    assessment: 'Not started',
    compatibility: 'Pending',
    complexity: 'Medium',
    dependencies: 'Commerce API',
    blockers: 'Assessment pending',
    readiness: 42,
    pattern: 'Assess',
    target: 'Retain / optimize',
    rationale: 'Insufficient evidence to justify migration in this wave.',
    benefit: 'Avoid premature investment while improving observability.',
    considerations: 'Run compatibility and performance assessment.',
  },
  {
    id: 'DB-1257',
    customer: 'Contoso Retail',
    application: 'Finance Close',
    database: 'FinanceLedger',
    engine: 'SQL Server',
    version: '2016 SP3',
    hosting: 'On-premises',
    size: '2.4 TB',
    criticality: 'Critical',
    eosRisk: 'Medium',
    azureState: 'ExpressRoute ready',
    assessment: 'Complete',
    compatibility: '98%',
    complexity: 'Medium',
    dependencies: 'SAP, Power BI',
    blockers: 'Quarter-end freeze window',
    readiness: 81,
    pattern: 'Rehost',
    target: 'SQL Server on Azure VM',
    rationale: 'Time-bound move with specialized third-party extensions.',
    benefit: 'Accelerate datacenter exit and retain full SQL surface area.',
    considerations: 'Modernize to PaaS after extension retirement.',
  },
  {
    id: 'DB-1289',
    customer: 'Fabrikam Energy',
    application: 'Asset Analytics',
    database: 'TelemetryMart',
    engine: 'SQL Server',
    version: '2022',
    hosting: 'Azure VM',
    size: '6.7 TB',
    criticality: 'High',
    eosRisk: 'Low',
    azureState: 'Azure-hosted',
    assessment: 'Complete',
    compatibility: '94%',
    complexity: 'Medium',
    dependencies: 'Event Hubs, Power BI',
    blockers: 'Data ingestion redesign',
    readiness: 78,
    pattern: 'Modernize',
    target: 'SQL Database in Microsoft Fabric',
    rationale: 'Analytics-first workload with strong Fabric adjacency.',
    benefit: 'Simplify data movement and accelerate insight delivery.',
    considerations: 'Benchmark high-volume ingestion and concurrency.',
  },
];

export const decisions = [
  { workload: 'RetailOps-Prod', recommendation: 'Azure SQL Managed Instance', decision: 'Approved', rationale: 'Datacenter exit priority', owner: 'Maya Chen', status: 'On track', nextAction: 'Complete landing zone review' },
  { workload: 'Dispatch-Core', recommendation: 'Azure SQL Database', decision: 'Approved', rationale: 'Low complexity quick win', owner: 'Owen Reed', status: 'Ready', nextAction: 'Schedule migration rehearsal' },
  { workload: 'BillingDW', recommendation: 'SQL Database in Microsoft Fabric', decision: 'Pending', rationale: 'Architecture validation required', owner: 'Priya Shah', status: 'At risk', nextAction: 'Resolve PL/SQL conversion spike' },
  { workload: 'MES-Plant07', recommendation: 'SQL Server on Azure Local', decision: 'Conditional', rationale: 'Plant resilience requirement', owner: 'Luis Torres', status: 'In review', nextAction: 'Run offline operations test' },
  { workload: 'Orders-Primary', recommendation: 'Retain / optimize', decision: 'Deferred', rationale: 'Assessment evidence incomplete', owner: 'Avery Jones', status: 'Planned', nextAction: 'Start discovery workshop' },
];
